/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */


/* Are we compiling for PS3? */
#define PS3_COMPILE


/* Define to 1 if you have the declaration of `sys_siglist', and to 0 if you
   don't. */
#define HAVE_DECL_SYS_SIGLIST 0

/* Enable Fullscreen support. */
//#define HAVE_FULLSCREEN 

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Can we use the JPEG library? */
//#define HAVE_JPEG 

/* Define to 1 if you have the `m' library (-lm). */
//#define HAVE_LIBM 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

#ifdef PS3_COMPILE
#define HUGE HUGE_VAL
#endif

/* Can we use the PNG library? */
//#define HAVE_PNG 

#define USE_PS3_AUDIO

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the <strings.h> header file. */
//#define HAVE_STRINGS_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `swab' function. */
#define HAVE_SWAB 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "vice"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Where do we want to install the executable? */
#define PREFIX "/usr/local"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Version number of package */
#define VERSION "2.1"

/* Define as `fork' if `vfork' does not work. */
#define vfork fork



#define HAVE_ALLOCA            1
#define HAVE_RESID             1
#define HAVE_RESID_FP          1
//#define HAVE_RESID_DTV         1
#define HAVE_PNG               1
#define HAVE_ZLIB              1
#define HAS_JOYSTICK           1
#define HAVE_MOUSE             1
//#define HAVE_NETWORK           1

//#define HAVE_CATWEASELMKIII    1
//#define HAVE_HARDSID           1
//#define HAVE_OPENCBM           1
//#define HAVE_DYNLIB_SUPPORT    1
//#define HAVE_RS232             1

#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG   4
#define SIZEOF_UNSIGNED_SHORT  2

#define HAVE_ATEXIT            1

#define HAVE_MEMMOVE           1
#define HAVE_STRERROR          1
#define HAVE_FCNTL_H           1
#define HAVE_LIMITS_H          1
#define HAVE_COMMCTRL_H        1
//#define HAVE_SHLOBJ_H          1
//#define HAVE_DIRECT_H          1
#define HAVE_DIRENT_H          1
#define HAVE_ERRNO_H           1
//#define HAVE_IO_H              1
#define HAVE_PROCESS_H         1
#define HAVE_SYS_TYPES_H       1
#define HAVE_SYS_STAT_H        1
//#define HAVE_SIGNAL_H          1

//#define DWORD_IS_LONG          1
#define HAVE_HTONS             1
//#define HAVE_GETCWD            1

